In [115]:
import glob
import pandas as pd
from pathlib import Path  
import numpy as np
# import geopandas as gpd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Re-formatting columns

In [116]:
# from geopy.distance import geodesic
all_stops = pd.read_csv('C:\\Users\\kharr\\Documents\\GitHub\\Berkeley-PD-ISF-110\\Data\\All_Stops_with_tracts(1).csv',keep_default_na=True)
all_stops.shape

C:\Users\kharr\anaconda3\envs\legal-studies\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (25,26) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

(61702, 55)

In [117]:
from geopy.distance import geodesic
newport_ri = (41.49008, -71.312796)
cleveland_oh = (41.499498, -81.695391)
print(geodesic(newport_ri, cleveland_oh).miles)

538.3904453677205

In [118]:
all_stops['Distance from Cal'] = 0
all_stops.head(2)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LEA Record ID,Incident Number,Date of Stop,Time of Stop,Duration of Stop,City,LAT,...,Citation Offense Codes,In field cite and release Offense Codes,Custodial arrest Offense Codes,IncidentNumber,Address,CallType,Car Search,censustract,forceused,Distance from Cal
0,0,0,0,BPD000021033,NaN,10/1/2020,11:14,8.0,Berkeley,37.855313,...,VC 23123(A) USE CELLPH W/DRIV W/O HFD (I) | VC...,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,0,0
1,1,41,41,BPD000021062,NaN,10/2/2020,15:21,7.0,Berkeley,37.854378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,1,0

In [119]:
all_stops_len = all_stops.index.size
all_stops_len

61702

In [120]:
%%time

i = 0
uni_coords = (37.8719,122.2585)

for i in range(all_stops.index.size):
    long_1 = (all_stops['LONG'][i])*-1
    lat_1 = all_stops['LAT'][i]
    stop_coords = (lat_1,long_1)
    distance = round(geodesic(stop_coords, uni_coords).miles,1)
    all_stops.loc[i,'Distance from Cal'] = distance
#     print(i)

Wall time: 25.3 s

In [121]:
all_stops.head(5)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,LEA Record ID,Incident Number,Date of Stop,Time of Stop,Duration of Stop,City,LAT,...,Citation Offense Codes,In field cite and release Offense Codes,Custodial arrest Offense Codes,IncidentNumber,Address,CallType,Car Search,censustract,forceused,Distance from Cal
0,0,0,0,BPD000021033,NaN,10/1/2020,11:14,8.0,Berkeley,37.855313,...,VC 23123(A) USE CELLPH W/DRIV W/O HFD (I) | VC...,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,0,1.2
1,1,41,41,BPD000021062,NaN,10/2/2020,15:21,7.0,Berkeley,37.854378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,1,1.4
2,2,52,52,BPD000021048,NaN,10/2/2020,5:04,10.0,Berkeley,37.859469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,0,1.0
3,3,63,63,BPD000021083,NaN,10/3/2020,18:57,23.0,Berkeley,37.855689,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,0,1.3
4,4,65,65,BPD000021126,NaN,10/3/2020,19:56,30.0,Berkeley,37.857611,...,NaN,NaN,PC 459 BURGLARY (F),NaN,NaN,NaN,NaN,4235.0,1,1.1

In [122]:
all_stops = all_stops.rename(columns={'Distance from Cal': 'distancefromcal'})
all_stops['Date of Stop'].dt
all_stops.drop(all_stops.iloc[:,0:3],inplace=True,axis=1)
all_stops.head(2)

,LEA Record ID,Incident Number,Date of Stop,Time of Stop,Duration of Stop,City,LAT,LONG,Race Perceived Prior To Stop,Perceived Race or Ethnicity,...,Citation Offense Codes,In field cite and release Offense Codes,Custodial arrest Offense Codes,IncidentNumber,Address,CallType,Car Search,censustract,forceused,distancefromcal
0,BPD000021033,NaN,10/1/2020,11:14,8.0,Berkeley,37.855313,-122.266571,True,Hispanic/Latino,...,VC 23123(A) USE CELLPH W/DRIV W/O HFD (I) | VC...,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,0,1.2
1,BPD000021062,NaN,10/2/2020,15:21,7.0,Berkeley,37.854378,-122.271169,True,Black/African American,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4235.0,1,1.4

In [133]:
berkeley_data['Date of Stop'] = pd.to_datetime(berkeley_data['Date of Stop'])
berkeley_data['mm'] = berkeley_data['Date of Stop'].dt.month
berkeley_data['yyyy'] = berkeley_data['Date of Stop'].dt.year

0       2020-10-01
1       2020-10-02
2       2020-10-02
3       2020-10-03
4       2020-10-03
           ...
61697   2019-10-07
61698   2019-10-07
61699   2019-10-23
61700   2019-09-25
61701   2016-04-08
Name: Date of Stop, Length: 61702, dtype: datetime64[ns]

In [134]:
filepath = Path('C:\\Users\\kharr\\Documents\\GitHub\\Berkeley-PD-ISF-110\\Data\\formatted_allstops_large.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
all_stops.to_csv(filepath, na_rep='')